---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidycensus)
library(fs)
library(sf)
library(assertr)

sel_tracts <- c("36047036600",
                  "36047036400",
                  "36047036200",
                  "36047036001",
                  "36047036002",
                  "36047061002",
                  "36047061004",
                  "36047061003")

colors <- c("#264653", "#2a9d8f", "#ca6702", "#9b2226", "#e9d8a6", "#b5179e", "#577590")
```
```{r}
## create map of census tracts
nta <- st_read("https://data.cityofnewyork.us/resource/93vf-i5bz.geojson") %>% 
  filter(str_detect(ntaname, "Brighton Beach"))
nta

tracts <- st_read("https://data.cityofnewyork.us/resource/i69b-3rdj.geojson?$limit=10000") %>% 
  filter(str_detect(ntaname, "Brighton Beach")) %>% 
  filter(ct2010 %in% str_replace_all(sel_tracts, "36047", ""))
tracts

tracts %>% 
  as.data.frame() %>% 
  verify(nrow(.) == 8)
```
```{r}
nta %>% 
  st_transform(2263) %>% 
  ggplot() +
  geom_sf(fill = NA, color = "black") +
  geom_sf(data = tracts, fill = colors[2], color = "gray", size = 1) +
  theme_void()

ggsave(path("02_output", "tract_map.png"))
```


```{r}
# load vars
vars <- readxl::read_excel(path("01_input", "census_vars.xlsx"), sheet = "allvars")
vars

varlist <- vars$varname
names(varlist) <- vars$label
varlist

vars_sub <- readxl::read_excel(path("01_input", "census_vars.xlsx"), sheet = "subset")
vars_sub
varlist_sub <- vars_sub$varname
names(varlist_sub) <- vars_sub$label
```
```{r}
rel_vars <- readxl::read_excel(path("01_input", "rel_file_vars.xlsx"))
rel_vars

rel_file <- read.csv(path("01_input", "2010_rel_file.csv"), skip = 1, header = F)

names(rel_file) <- rel_vars$varname
rel_file %>% 
  filter(GEOID10 %in% sel_tracts) %>% 
  select(c("HUPCT00", "HUPCT10"))
```

```{r}
get_acs_yr <- function(yr, vars){
  get_acs(geography = "tract", 
              variables = vars, 
              state = "NY", 
              county = "047",
              year = yr)  %>% 
  filter(GEOID %in% sel_tracts) %>% 
           mutate(year = yr)
}

varlist
  
varlist_rent <- varlist[(length(varlist)-6)]
varlist_rent
```

```{r}
df_19 <- get_acs(geography = "tract",
          variable  = varlist,
          state = "NY",
          county = "047",
<<<<<<< HEAD
          year = 2019) %>% 
  mutate(year = 2019)

df_14 <- get_acs(geography = "tract",
          variable  = varlist[c(1:20, 40:(length(varlist) - 7))],
          state = "NY",
          county = "047",
          year = 2014) %>% 
  mutate(year = 2014)

df_09 <- get_acs(geography = "tract",
          variable  = varlist[c(40:(length(varlist) - 7))],
          state = "NY",
          county = "047",
          year = 2009) %>% 
  mutate(year = 2009)
```
```{r}
 df_full <- rbind(df_19, df_14, df_09) %>% 
  filter(GEOID %in% sel_tracts) %>% 
  mutate(year_lab = case_when(year == 2014 ~ "2010-2014",
                          year == 2019 ~ "2015-2019",
                          year == 2009 ~ "2005-2009"),
=======
          year = 2019)

df_14 <- get_acs(geography = "tract",
          variable  = varlist,
          state = "NY",
          county = "047",
          year = 2014)

df_19  %>% 
  #filter(GEOID %in% sel_tracts) %>% 
  filter(str_detect(variable, "rent")) %>% 
  group_by(variable) %>% 
  summarize(mean = mean(estimate, na.rm = T))
```
```{r}
df <- map_dfr(c(2009, 2014, 2019), ~get_acs_yr(., varlist))
df %>%
  pull(year) %>%
  unique()

# df_sub <- map_dfr(c(2014, 2019), ~get_acs_yr(., varlist_sub))
# df_sub %>% 
#   write_csv(path("02_output", "subset_data.csv"), na = "")

 df_full <- df_full #rbind(df, df_sub) %>% 
  mutate(year_lab = case_when(year == 2009 ~ "2005-2009",
                          year == 2014 ~ "2010-2014",
                          year == 2019 ~ "2015-2019"),
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
    year_lab = factor(year_lab,
                       levels = c("2005-2009", "2010-2014", "2015-2019"),
                       ordered = T),
    tract_name = str_replace_all(NAME, ", Kings County, New York",""))
<<<<<<< HEAD
=======

# df_full %>% 
#   write_csv(path("02_output", "census_full.csv"), na = "")
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
```
```{r}
label_det <- vars$label_det
label <- vars$label

vars_order <- vars %>% 
  filter(str_detect(label, "female")) %>% 
  filter(label != "female_total") %>% 
  pull(label_det)

stopifnot(length(label) == length(label_det))
```

```{r}
df_full %>% 
  filter(year == 2019) %>% 
  filter(str_detect(variable, "male")) %>% 
  filter(!(variable %in% c("male_total", "female_total"))) %>% 
  group_by(variable) %>%
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(per = estimate * 100 / sum(estimate, na.rm = T)) %>% 
  mutate(gender = if_else(str_detect(variable, "female"), "Female", "Male"),
         age_cat = factor(label_det[match(variable, label)],
                          levels = vars_order,
                          ordered = T))

df_19 %>% 
  filter(str_detect(variable, "male")) %>% 
  filter(!(variable %in% c("male_total", "female_total"))) %>% 
  group_by(variable) %>%
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(per = estimate * 100 / sum(estimate, na.rm = T)) %>% 
  mutate(gender = if_else(str_detect(variable, "female"), "Female", "Male"),
         age_cat = factor(label_det[match(variable, label)],
                          levels = vars_order,
                          ordered = T))
# %>% 
#   filter(age_cat %in% c("10 to 14 years", "Under 5 years", "5 to 9 years",
#                         "15 to 17 years", "18 and 19 years")) %>% 
#   summarize(per = sum(per, na.rm = T))
```

```{r}
<<<<<<< HEAD
df_full %>%
  filter(year == 2019) %>% 
=======
df_19 %>% 
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
  filter(str_detect(variable, "male")) %>% 
  filter(!(variable %in% c("male_total", "female_total"))) %>% 
  group_by(variable) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(per = estimate * 100 / sum(estimate, na.rm = T)) %>% 
  mutate(gender = if_else(str_detect(variable, "female"), "Female", "Male"),
         age_cat = factor(label_det[match(variable, label)],
                          levels = vars_order,
                          ordered = T)) %>% 
  mutate(per = if_else(gender == "Male", -1*per, per)) %>% 
  ggplot() +
  geom_col(aes(age_cat, per, fill = gender)) +
  coord_flip() +
  theme_classic() +
  labs(y = "Percent of total population",
       x = "") +
  scale_fill_manual(name = "",
                    values = colors,
                    guide = guide_legend(reverse=TRUE)) +
  scale_y_continuous(breaks = c(-7.5, -5, -2.5, 0, 2.5, 5, 7.5),
                     labels = c("-7.5%", "-5%", "-2.5%", "0%", "2.5%",
                                "5%", "7.5%")) +
    theme(legend.position="bottom")

ggsave(path("02_output", "population_pyramid.png"))
```
<<<<<<< HEAD

```{r, fig.width = 12}
library(magrittr)
df_full %>% 
  filter(variable == "nhpi_race", year == 2019) %>% 
  pull(estimate) %>% 
  equals(0) %>% 
  all() %>% 
  stopifnot()

=======
```{r, fig.width = 12}
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
df_full %>% 
  filter(str_detect(variable, "_race") | str_detect(variable, "_eth")) %>% 
  group_by(year_lab, variable) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  filter(!(variable %in% c("total_race", "total_eth", "nothisp_eth",
                           "multnoth_race",
                           "multoth_race",
                           "nhpi_race"))) %>% 
<<<<<<< HEAD
  mutate(raceeth_lab = case_when(variable == "black_race" ~ "Black or\nAfrican American",
=======
  mutate(eth_lab = case_when(variable == "black_race" ~ "Black or\nAfrican American",
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
                              variable == "aian_race" ~ "American Indian or\nAlaskan Native",
                              variable == "nhpi_race" ~ "Native Hawaiian or\nPacific Islander",
                              variable == "asian_race" ~ "Asian",
                              variable == "white_race" ~ "White",
                              variable == "oth_race" ~ "Other race",
                              variable == "mult_race" ~ "Two or more races",
                              variable == "hisp_eth" ~ "Hispanic or Latinx",
                              TRUE ~ NA_character_),
<<<<<<< HEAD
         raceeth_lab = factor(raceeth_lab, levels = c("Black or\nAfrican American",
=======
         eth_lab = factor(race_lab, levels = c("Black or\nAfrican American",
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
                                                "Hispanic or Latinx",
                                                "Asian",
                                                "White",
                                                "Native Hawaiian or\nPacific Islander",
                                                "American Indian or\nAlaskan Native",
                                                "Two or more races",
                                                "Other race"),
                           ordered = T)) %>% 
<<<<<<< HEAD
  assertr::verify(!is.na(raceeth_lab)) %>% 
  ggplot(aes(raceeth_lab, estimate, fill = year_lab, group = year_lab)) +
=======
  assertr::verify(!is.na(race_lab)) %>% 
  ggplot(aes(race_lab, estimate, fill = year_lab, group = year_lab)) +
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
  geom_col(width = 0.8,
           position = position_dodge(width = 0.9)) +
  geom_text(aes(group = year_lab,
                label = if_else(estimate == 0, NA_character_,
                                scales::comma(estimate, accuracy = 1))),
            position = position_dodge(width = 0.9),
            size = 3.5,
            vjust = -1,
            hjust = 0.5) +
  theme_classic() +
  theme(plot.caption = element_text(hjust = 0)) + 
  labs(x = "Race/ethnicity",
       y = "Number of people",
       fill = "ACS 5-year Survey",
<<<<<<< HEAD
       caption = "Note: Native Hawaiian and Pacific Islander is not shown because total counts were 0 in all survey years.") +
=======
       caption = "Note: Native Hawaiian and Pacific Islander race category is not shown because total counts were 0 in all three survey years.") +
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
  scale_y_continuous(label=scales::comma) +
  scale_fill_manual(values = colors)
  
ggsave(path("02_output", "race_eth.png"),
       width = 12)
```
```{r}
total <- df_full %>% 
  filter(variable == "total_race") %>%
  filter(year == 2019) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  verify(nrow(.) == 1) %>% 
  pull(estimate)

df_full %>% 
  filter(str_detect(variable, "_race")) %>% 
  filter(!(variable %in% c("total_race", "multoth_race", "multnoth_race"))) %>% 
  filter(year == 2019) %>% 
<<<<<<< HEAD
  mutate(raceeth_lab = case_when(variable == "black_race" ~ "Black or\nAfrican American",
=======
  mutate(eth_lab = case_when(variable == "black_race" ~ "Black or\nAfrican American",
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
                              variable == "aian_race" ~ "American Indian or\nAlaskan Native",
                              variable == "nhpi_race" ~ "Native Hawaiian or\nPacific Islander",
                              variable == "asian_race" ~ "Asian",
                              variable == "white_race" ~ "White",
                              variable == "oth_race" ~ "Other race",
                              variable == "mult_race" ~ "Two or more races",
                              variable == "hisp_eth" ~ "Hispanic or Latinx",
                              TRUE ~ NA_character_),
<<<<<<< HEAD
         raceeth_lab = factor(raceeth_lab, levels = c("Black or\nAfrican American",
=======
         eth_lab = factor(race_lab, levels = c("Black or\nAfrican American",
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
                                                "Hispanic or Latinx",
                                                "Asian",
                                                "White",
                                                "Native Hawaiian or\nPacific Islander",
                                                "American Indian or\nAlaskan Native",
                                                "Two or more races",
                                                "Other race"),
                           ordered = T)) %>% 
<<<<<<< HEAD
  assertr::verify(!is.na(raceeth_lab))  %>% 
  group_by(raceeth_lab) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  mutate(per = round(estimate * 100 / total)) %>%
  ungroup() %>% 
  arrange(desc(raceeth_lab)) %>% 
  mutate(ypos = cumsum(per)- 0.5*per) %>% 
  ggplot(aes(x="", y=per, fill=raceeth_lab))+
=======
  assertr::verify(!is.na(race_lab))  %>% 
  group_by(race_lab) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  mutate(per = round(estimate * 100 / total)) %>%
  ungroup() %>% 
  arrange(desc(race_lab)) %>% 
  mutate(ypos = cumsum(per)- 0.5*per) %>% 
  ggplot(aes(x="", y=per, fill=race_lab))+
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  geom_text(aes(label = if_else(per > 1, per, NA_real_)),
            position = position_stack(vjust = 0.5)) +
<<<<<<< HEAD
  scale_fill_manual(values = colors[c(2,1,3:length(colors))],
=======
  scale_fill_manual(values = colors,
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
                    name = "")

ggsave(path("02_output", "race_2019.png"))
```

```{r}
total <- df_full %>% 
  filter(variable == "total_eth") %>%
  filter(year == 2019) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  verify(nrow(.) == 1) %>% 
  pull(estimate)

df_full %>% 
  filter(str_detect(variable, "_eth")) %>% 
  filter(!(variable %in% c("total_eth"))) %>% 
  filter(year == 2019) %>% 
  mutate(eth_lab = case_when(variable == "nothisp_eth" ~ "Not Hispanic or Latinx",
                              variable == "hisp_eth" ~ "Hispanic or Latinx",
                              TRUE ~ NA_character_),
         eth_lab = factor(eth_lab, levels = c("Not Hispanic or Latinx",
                                                "Hispanic or Latinx"),
                           ordered = T)) %>% 
  assertr::verify(!is.na(eth_lab))  %>% 
  group_by(eth_lab) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  mutate(per = round(estimate * 100 / total)) %>%
  ungroup() %>% 
  arrange(desc(eth_lab)) %>% 
  mutate(ypos = cumsum(per)- 0.5*per) %>% 
  ggplot(aes(x="", y=per, fill=eth_lab))+
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  geom_text(aes(label = if_else(per > 1, per, NA_real_)),
            position = position_stack(vjust = 0.5),
            color = "white") +
  scale_fill_manual(values = colors,
                    name = "")

ggsave(path("02_output", "eth_2019.png"))
```

## Population projection
```{r}
## how did the population change over the past
df_full %>%
<<<<<<< HEAD
  filter(variable == "total_race") %>% 
=======
  filter(variable == "total") %>% 
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
  group_by(year) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  ungroup() %>% 
  ggplot(aes(year, estimate)) +
  geom_line(color = colors[1]) +
  theme_classic() +
<<<<<<< HEAD
  scale_y_continuous(limits = c(0, 35000),
=======
  scale_y_continuous(limits = c(0, 23000),
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
                     label=scales::comma) +
  scale_x_continuous(breaks = c(2009, 2014, 2019),
                     labels = c("2005-2009", "2010-2014",
                                "2015-2019")) + 
  labs(x = "ACS 5-Year Survey",
       y = "Number of People")

ggsave(path("02_output", "population_time.png"))
```

Formula: P_2040 = P_2020 * (G_{2020-2030} + 100) * (G_{2030-2040} + 100)
```{r}
df_full %>%
<<<<<<< HEAD
  filter(variable == "total_race") %>% 
=======
  filter(variable == "total") %>% 
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
  group_by(year) %>% 
  summarize(estimate = sum(estimate, na.rm =T))

pop_2020 <- df_full %>%
<<<<<<< HEAD
  filter(variable == "total_race") %>% 
  filter(year == 2019) %>% 
=======
  filter(variable == "total") %>% 
  filter(year == 2019) %>% 
  assertr::verify(nrow(.) == 5) %>% 
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  pull(estimate)
pop_2020
```

```{r}
<<<<<<< HEAD
pop_2040 <- pop_2020 * (1.04)  * (1.031)
=======
pop_2040 <- 18663 * (1.04)  * (1.031)
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
pop_2040

round(pop_2040 - pop_2020)
```
## Examine median hh income

```{r}
df_full %>% 
  filter(variable == "med_hhinc")  %>% 
  bind_rows(
    df_full %>% 
      group_by(year) %>% 
      filter(variable == "med_hhinc") %>% 
      summarize(estimate = mean(estimate, na.rm = T)) %>% 
      mutate(tract_name = "Average")
  ) %>% 
  ggplot() +
  geom_line(aes(year,
                estimate, color = tract_name)) +
  theme_classic() +
  scale_x_continuous(breaks = c(2009, 2014, 2019),
<<<<<<< HEAD
                     labels = c("2005-2009", "2010-2014","2015-2019"))+
  scale_y_continuous(label=scales::comma) +
  # scale_color_manual(values = colors,
  #                    name = "Tract Name") +
  labs(color = "Tract Name") +
=======
                     labels = c("2005-2009", "2010-2014","2015-2019")) +
  scale_y_continuous(label=scales::comma) +
  scale_color_manual(values = colors,
                     name = "Tract Name") +
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9
  labs(x = "ACS 5-Year Survey",
       y = "Median Household Income ($)")

ggsave(path("02_output", "median_hhinc.png"))
```

```{r}
df_full %>% 
  group_by(year_lab, variable) %>% 
  summarize(estimate = sum(estimate, na.rm = T)) %>% 
  filter(variable %in% c("hh_oo",
                         "hh_ro",
                         "total_hh")) %>% 
  pivot_wider(id_cols = c("year_lab"),
              names_from = "variable",
              values_from = "estimate") %>% 
  mutate(per_oo = round(100 * hh_oo / total_hh),
         per_ro = round(100 * hh_ro / total_hh)) %>% 
  pivot_longer(cols = c("per_oo", "per_ro")) %>% 
  mutate(desc = if_else(name == "per_oo", "Owner occupied", "Renter occupied")) %>% 
  ggplot(aes(year_lab, value, fill = desc, group = desc)) +
  geom_col() +
  geom_text(aes(label = str_c(value, "%")), position = "stack",
            vjust = 1.5, color = "white") +
  theme_classic() +
  scale_fill_manual(values = colors, name = "") +
  labs(x = "ACS 5-Year Survey",
       y = "Share of Total Households")

ggsave(path("02_output", "share_hh.png"))
```
```{r}
df_full %>% 
  filter(variable %in% c("same_hh", "total_hh_move")) %>% 
  select(-"moe") %>% 
  pivot_wider(id_cols = -c("variable"), names_from = "variable", values_from = "estimate") %>% 
  mutate(moved_hh = total_hh_move - same_hh) %>% 
  pivot_longer(cols = c("moved_hh", "same_hh")) %>% 
  group_by(year_lab, name) %>% 
  summarize(estimate = sum(value, na.rm = T)) %>% 
  group_by(year_lab) %>% 
  mutate(per = estimate * 100 / sum(estimate, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(var_lab = case_when(name == "same_hh" ~ "Same house 1 year ago",
                             name == "moved_hh" ~ "Moved since 1 year ago",
                             TRUE ~ NA_character_)) %>% 
  ggplot(aes(year_lab, per, fill = var_lab)) +
  geom_col() +
  labs(x = "ACS 5-Year Survey",
       y = "Percent of all households",
       fill = "") +
  geom_text(aes(label = str_c(round(per), "%")), position = "stack",
            vjust = 1.1, color = "white") +
  theme_classic() +
  scale_fill_manual(values = colors) 

ggsave(path("02_output", "movement.png"))
```


<<<<<<< HEAD
## Maps

```{r}
boros <- st_read("https://data.cityofnewyork.us/resource/7t3b-ywvw.geojson") %>% 
  st_transform(2263) %>% 
  filter(boro_name == "Brooklyn")

nta %>% 
  st_transform(2263) %>% 
  ggplot() +
  geom_sf(data = boros, fill = NA, color = "black") +
  geom_sf(fill = NA, color = colors[2]) +
  theme_void()

ggsave(path("02_output", "tract_map2.png"))
```
=======
>>>>>>> c058bd84d06683827e7a290d87ba40b13f28bde9





